version: '{build}'
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package
  - cd %APPVEYOR_BUILD_FOLDER%
artifacts:
    path: target\*.jar
    name: WataDefense